version: "3"
services:
  reverseproxy:
      image: wpthein/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: wpthein/udacity-restapi-user
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRESS_PASSWORD: postgres 
      POSTGRESS_DB: udagramdev 
      POSTGRESS_HOST: udagramdev.chhjjps1fatp.us-east-1.rds.amazonaws.com 
      AWS_REGION: us-east-1 
      AWS_PROFILE: default 
      AWS_BUCKET: udagram-win-dev
      JWT_SECRET: winphyothein
      URL: "http://192.168.99.101:8100"
  backend-feed:
    image: wpthein/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRESS_PASSWORD: postgres 
      POSTGRESS_DB: udagramdev 
      POSTGRESS_HOST: udagramdev.chhjjps1fatp.us-east-1.rds.amazonaws.com 
      AWS_REGION: us-east-1 
      AWS_PROFILE: default 
      AWS_BUCKET: udagram-win-dev
      JWT_SECRET: winphyothein
      URL: "http://192.168.99.101:8100"
  frontend:
    image: wpthein/udacity-frontend:local
    ports:
      - "8100:80"
