apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
    POSTGRESS_USERNAME: postgres
    POSTGRESS_PASSWORD: postgres 
    POSTGRESS_DB: udagramdev 
    POSTGRESS_HOST: udagramdev.chhjjps1fatp.us-east-1.rds.amazonaws.com 
    AWS_REGION: us-east-1 
    AWS_PROFILE: default 
    AWS_BUCKET: udagram-win-dev
    JWT_SECRET: winphyothein
    URL: "http://localhost:8100"